### ISSUE TITLE
The GitHub workflow for publishing a release does not work

### ISSUE THREAD

**Issue by fohrloop** [fohrloop/wakepy#300]
The Github workflow for publishing a release (.github/workflows/publish-a-release.yml ) does not work. 

- It triggers when PR is merged to main, but does not run the release step as those start like this:

```
  publish-to-github-releases:
    name: Publish wakepy to GitHub
    # only publish to GitHub Releases on tag pushes
    if: startsWith(github.ref, 'refs/tags/')
```

- It can be triggered manually, but does not run the release step for the same above mentioned reason.
- It will not trigger on tag push. The yaml starts with:

```
'on':
  workflow_dispatch:
  push:
    branches:
      - main

```
